version: '3.8'

services:
  discovery-service:
    image: discovery-service:latest
    build: .
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
